// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR6nkkpN3kUG6Fp_uNz0C-XXtNKkUE9xA',
    appId: '1:969055211829:web:f8164ff86ea830c815bc7c',
    messagingSenderId: '969055211829',
    projectId: 'pleasehiretolga',
    authDomain: 'pleasehiretolga.firebaseapp.com',
    storageBucket: 'pleasehiretolga.firebasestorage.app',
    measurementId: 'G-36YE5VY7L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8ZaztF_Bkq0jLSVK7GBfhYA4c-Xq4Vk',
    appId: '1:969055211829:android:7bab5394a8142dbd15bc7c',
    messagingSenderId: '969055211829',
    projectId: 'pleasehiretolga',
    storageBucket: 'pleasehiretolga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWYX9qbNAWxNEYG7PcDsiXtPWKzMBBF0',
    appId: '1:969055211829:ios:b2c3ffc68d23738d15bc7c',
    messagingSenderId: '969055211829',
    projectId: 'pleasehiretolga',
    storageBucket: 'pleasehiretolga.firebasestorage.app',
    iosBundleId: 'dev.tysoftware.pleasehiretolga',
  );
}
