name: pleasehiretolga
description: "A new Flutter project."
publish_to: "none"
version: 1.2.8
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  flutter_hooks: ^0.21.2
  firebase_auth: ^5.5.3
  hooks_riverpod: ^2.6.1
  dart_mappable: ^4.5.0
  intl: ^0.19.0
  go_router: ^15.1.1
  auto_size_text: ^3.0.0
  cloud_firestore: ^5.6.7
  url_launcher: ^6.3.1
  mobile_scanner: ^7.0.0
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  meta: ^1.16.0
  flutter_native_splash: ^2.4.6
  confetti: ^0.8.0
  flutter_markdown: ^0.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  flutter_gen_runner: ^5.10.0
  firebase_auth_mocks: ^0.14.1
  fake_cloud_firestore: ^3.1.0
  firebase_storage_mocks: ^0.7.0
  flutter_launcher_icons: ^0.14.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Black.ttf
          weight: 900
        - asset: assets/font/DMSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/font/DMSans-Bold.ttf
          weight: 700
        - asset: assets/font/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/font/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/font/DMSans-Italic.ttf
          style: italic
        - asset: assets/font/DMSans-Light.ttf
          weight: 300
        - asset: assets/font/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/DMSans-Medium.ttf
          weight: 500
        - asset: assets/font/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/DMSans-Regular.ttf
        - asset: assets/font/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/DMSans-Thin.ttf
          weight: 100
        - asset: assets/font/DMSans-ThinItalic.ttf
          weight: 100
          style: italic

flutter_gen:
  output: lib/core/gen/
  line_length: 80

flutter_native_splash:
  background_image: assets/images/bg_image.jpg
  image: assets/images/app_icon_without_bg.png

  android_12:
    color: "#a166b7"

  ios: true
  android: true
  web: false
